/* ************************************************************************
* Copyright (C) 2025-2026 Advanced Micro Devices, Inc.
*
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in
* all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS") WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
* THE SOFTWARE.
*
* ************************************************************************ */
#include <cstdint>
#include <iostream>
#include <string>
#include <utility>

#include "gfx/CommonInstsDSL.hpp"
#include "gfx/InstDefDSL.hpp"

namespace stinkytofu
{
    namespace
    {
        //=======================================================================
        // INSTRUCTION METADATA FOR GFX950
        //=======================================================================
        //
        // Instruction costs and definitions are GENERATED from .def files:
        //   - hardware/defs/Gfx950Formats.def, Gfx950Instructions.def
        //   - Build with tablegen to produce hardware/generated/Gfx950_*.inc
        //
        // Related metadata in other files:
        //   - Operand REQUIREMENTS (register width/type) -> Gfx950.hpp
        //
        // To modify instructions: edit the .def files and rebuild.
        //
        //=======================================================================

        // Instruction cost structure (used by generated _costs.inc)
        struct InstructionCost
        {
            const char* opcode;
            uint16_t    cycle;
            uint16_t    latency;
        };

        // Instruction costs: generated from hardware/defs/Gfx950Instructions.def
#include "hardware/generated/Gfx950_costs.inc"

        // Gfx950 default costs (CDNA3 architecture)
        constexpr uint16_t GFX950_DEFAULT_CYCLE   = 4;
        constexpr uint16_t GFX950_DEFAULT_LATENCY = 4;
    }

    void defineGfx950Insts(GpuArch& registry)
    {
        // Instruction definitions: generated from hardware/defs/Gfx950Instructions.def
#include "hardware/generated/Gfx950_init.inc"

        // Set wavefront size for gfx950
        registry.setWaveFrontSize(64);

        // Set register limits for gfx950 (GFX9 architecture)
        GpuArch::RegisterLimits limits;
        limits.maxVGPR = 256; // Vector GPRs: v0-v255
        limits.maxSGPR = 102; // Scalar GPRs: s0-s101 (GFX9 has 102 SGPRs)
        limits.maxAGPR = 256; // Accumulator GPRs: a0-a255
        registry.setRegisterLimits(limits);

        // Set default costs (REQUIRED!)
        registry.setDefaultCosts(GFX950_DEFAULT_CYCLE, GFX950_DEFAULT_LATENCY);

        // Register instruction-specific costs (exceptions from defaults)
        for(const auto& cost : Gfx950_GENERATED_COSTS)
        {
            registry.setInstructionCost(cost.opcode, cost.cycle, cost.latency);
        }

        // Apply costs with strict validation
        if(!registry.applyInstructionCosts())
        {
            std::cerr << "FATAL: Failed to apply instruction costs for Gfx950\n";
            return;
        }
    }

    // Rocisa (tensilelite) type name -> mnemonic; original map (pre-66fabbd) for RocisaGfx950Mappings.inc.
    void setGfx950RocisaToArchMap(GpuArch& registry)
    {
        std::unordered_map<std::string, std::string> rocisaToArchMap = {
            {"VCvtScalePkFP8toF16", "v_cvt_scalef32_pk_f16_fp8"},
            {"VCvtScalePkBF8toF16", "v_cvt_scalef32_pk_f16_bf8"},
            {"VCvtScaleFP8toF16", "v_cvt_scalef32_f16_fp8"},
            {"VCvtScalePkF16toFP8", "v_cvt_scalef32_pk_fp8_f16"},
            {"VCvtScalePkF16toBF8", "v_cvt_scalef32_pk_bf8_f16"},
            {"VCvtScaleSRF16toFP8", "v_cvt_scalef32_sr_fp8_f16"},
            {"VCvtScaleSRF16toBF8", "v_cvt_scalef32_sr_bf8_f16"},
            {"VDot2F32BF16", "v_dot2_f32_bf16"},
            {"VDot2CF32BF16", "v_dot2c_f32_bf16"},
            {"PVCvtBF16toFP32", "v_cvt_f32_bf16"},
            {"VCvtPkF32toBF16", "v_cvt_pk_bf16_f32"},
            {"DSLoadB64TrB16", "ds_read_b64_tr_b16"},
            /* branch.hpp */
            {"SBranch", "s_branch"},
            {"SCBranchSCC0", "s_cbranch_scc0"},
            {"SCBranchSCC1", "s_cbranch_scc1"},
            {"SCBranchVCCNZ", "s_cbranch_vccnz"},
            {"SCBranchVCCZ", "s_cbranch_vccz"},
            {"SSetPCB64", "s_setpc_b64"},
            {"SSwapPCB64", "s_swappc_b64"},
            {"SCBranchExecZ", "s_cbranch_execz"},
            {"SCBranchExecNZ", "s_cbranch_execnz"},
            /* cmp.hpp */
            {"SCmpEQI32", "s_cmp_eq_i32"},
            {"SCmpEQU32", "s_cmp_eq_u32"},
            {"SCmpEQU64", "s_cmp_eq_u64"},
            {"SCmpGeI32", "s_cmp_ge_i32"},
            {"SCmpGeU32", "s_cmp_ge_u32"},
            {"SCmpGtI32", "s_cmp_gt_i32"},
            {"SCmpGtU32", "s_cmp_gt_u32"},
            {"SCmpLeI32", "s_cmp_le_i32"},
            {"SCmpLeU32", "s_cmp_le_u32"},
            {"SCmpLgU32", "s_cmp_lg_u32"},
            {"SCmpLgI32", "s_cmp_lg_i32"},
            {"SCmpLgU64", "s_cmp_lg_u64"},
            {"SCmpLtI32", "s_cmp_lt_i32"},
            {"SCmpLtU32", "s_cmp_lt_u32"},
            {"SBitcmp1B32", "s_bitcmp1_b32"},
            {"SCmpKEQU32", "s_cmpk_eq_u32"},
            {"SCmpKGeU32", "s_cmpk_ge_u32"},
            {"SCmpKGtU32", "s_cmpk_gt_u32"},
            {"SCmpKLGU32", "s_cmpk_lg_u32"},
            {"VCmpEQF32", "v_cmp_eq_f32"},
            {"VCmpEQF64", "v_cmp_eq_f64"},
            {"VCmpEQU32", "v_cmp_eq_u32"},
            {"VCmpEQI32", "v_cmp_eq_i32"},
            {"VCmpGEF16", "v_cmp_ge_f16"},
            {"VCmpGTF16", "v_cmp_gt_f16"},
            {"VCmpGEF32", "v_cmp_ge_f32"},
            {"VCmpGTF32", "v_cmp_gt_f32"},
            {"VCmpGEF64", "v_cmp_ge_f64"},
            {"VCmpGTF64", "v_cmp_gt_f64"},
            {"VCmpGEI32", "v_cmp_ge_i32"},
            {"VCmpGTI32", "v_cmp_gt_i32"},
            {"VCmpGEU32", "v_cmp_ge_u32"},
            {"VCmpGtU32", "v_cmp_gt_u32"},
            {"VCmpLeU32", "v_cmp_le_u32"},
            {"VCmpLeI32", "v_cmp_le_i32"},
            {"VCmpLtI32", "v_cmp_lt_i32"},
            {"VCmpLtU32", "v_cmp_lt_u32"},
            {"VCmpUF32", "v_cmp_u_f32"},
            {"VCmpNeI32", "v_cmp_ne_i32"},
            {"VCmpNeU32", "v_cmp_ne_u32"},
            {"VCmpNeU64", "v_cmp_ne_u64"},
            {"VCmpClassF32", "v_cmp_class_f32"},
            {"VCmpXClassF32", "v_cmpx_class_f32"},
            {"VCmpXEqU32", "v_cmpx_eq_u32"},
            {"VCmpXGeU32", "v_cmpx_ge_u32"},
            {"VCmpXGtU32", "v_cmpx_gt_u32"},
            {"VCmpXLeU32", "v_cmpx_le_u32"},
            {"VCmpXLeI32", "v_cmpx_le_i32"},
            {"VCmpXLtF32", "v_cmpx_lt_f32"},
            {"VCmpXLtI32", "v_cmpx_lt_i32"},
            {"VCmpXLtU32", "v_cmpx_lt_u32"},
            {"VCmpXLtU64", "v_cmpx_lt_u64"},
            {"VCmpXNeU16", "v_cmpx_ne_u16"},
            {"VCmpXNeU32", "v_cmpx_ne_u32"},
            /* cvt.hpp */
            {"VCvtF16toF32", "v_cvt_f32_f16"},
            {"VCvtF32toF16", "v_cvt_f16_f32"},
            {"VCvtF32toU32", "v_cvt_u32_f32"},
            {"VCvtU32toF32", "v_cvt_f32_u32"},
            {"VCvtI32toF32", "v_cvt_f32_i32"},
            {"VCvtF32toI32", "v_cvt_i32_f32"},
            {"VCvtFP8toF32", "v_cvt_f32_fp8"},
            {"VCvtBF8toF32", "v_cvt_f32_bf8"},
            {"VCvtPkFP8toF32", "v_cvt_pk_f32_fp8"},
            {"VCvtPkBF8toF32", "v_cvt_pk_f32_bf8"},
            {"VCvtPkF32toFP8", "v_cvt_pk_fp8_f32"},
            {"VCvtPkF32toBF8", "v_cvt_pk_bf8_f32"},
            {"VCvtSRF32toFP8", "v_cvt_sr_fp8_f32"},
            {"VCvtSRF32toBF8", "v_cvt_sr_bf8_f32"},
            /* mem.hpp */
            {"BufferLoadU8", "buffer_load_ubyte"},
            {"BufferLoadD16HIU8", "buffer_load_ubyte_d16_hi"},
            {"BufferLoadD16U8", "buffer_load_ubyte_d16"},
            {"BufferLoadD16HIB16", "buffer_load_short_d16_hi"},
            {"BufferLoadD16B16", "buffer_load_short_d16"},
            {"BufferLoadB32", "buffer_load_dword"},
            {"BufferLoadB64", "buffer_load_dwordx2"},
            {"BufferLoadB128", "buffer_load_dwordx4"},
            {"FlatLoadD16HIU8", "flat_load_ubyte_d16_hi"},
            {"FlatLoadD16U8", "flat_load_ubyte_d16"},
            {"FlatLoadD16HIB16", "flat_load_short_d16_hi"},
            {"FlatLoadD16B16", "flat_load_short_d16"},
            {"FlatLoadB32", "flat_load_dword"},
            {"FlatLoadB64", "flat_load_dwordx2"},
            {"FlatLoadB128", "flat_load_dwordx4"},
            {"BufferStoreB8", "buffer_store_byte"},
            {"BufferStoreD16HIU8", "buffer_store_byte_d16_hi"},
            {"BufferStoreD16HIB16", "buffer_store_short_d16_hi"},
            {"BufferStoreB16", "buffer_store_short"},
            {"BufferStoreB32", "buffer_store_dword"},
            {"BufferStoreB64", "buffer_store_dwordx2"},
            {"BufferStoreB128", "buffer_store_dwordx4"},
            {"BufferAtomicAddF32", "buffer_atomic_add_f32"},
            {"BufferAtomicCmpswapB32", "buffer_atomic_cmpswap"},
            {"BufferAtomicCmpswapB64", "buffer_atomic_cmpswap_x2"},
            {"FlatStoreD16HIB16", "flat_store_short_d16_hi"},
            {"FlatStoreB32", "flat_store_dword"},
            {"FlatStoreB64", "flat_store_dwordx2"},
            {"FlatStoreB128", "flat_store_dwordx4"},
            {"FlatAtomicCmpswapB32", "flat_atomic_cmpswap"},
            {"DSLoadU8", "ds_read_u8"},
            {"DSLoadD16HIU8", "ds_read_u8_d16_hi"},
            {"DSLoadU16", "ds_read_u16"},
            {"DSLoadD16HIU16", "ds_read_u16_d16_hi"},
            {"DSLoadB16", "ds_read_u16"},
            {"DSLoadB32", "ds_read_b32"},
            {"DSLoadB64", "ds_read_b64"},
            {"DSLoadB128", "ds_read_b128"},
            {"DSLoad2B32", "ds_read2_b32"},
            {"DSLoad2B64", "ds_read2_b64"},
            {"DSStoreU16", "ds_write_b16"},
            {"DSStoreB8", "ds_write_b8"},
            {"DSStoreB16", "ds_write_b16"},
            {"DSStoreB8HID16", "ds_write_b8_d16_hi"},
            {"DSStoreD16HIB16", "ds_write_b16_d16_hi"},
            {"DSStoreB32", "ds_write_b32"},
            {"DSStoreB64", "ds_write_b64"},
            {"DSStoreB128", "ds_write_b128"},
            {"DSStore2B32", "ds_write2_b32"},
            {"DSStore2B64", "ds_write2_b64"},
            {"DSBPermuteB32", "ds_bpermute_b32"},
            {"SAtomicDec", "s_atomic_dec"},
            {"SLoadB32", "s_load_dword"},
            {"SLoadB64", "s_load_dwordx2"},
            {"SLoadB128", "s_load_dwordx4"},
            {"SLoadB256", "s_load_dwordx8"},
            {"SLoadB512", "s_load_dwordx16"},
            {"SStoreB32", "s_store_dword"},
            {"SStoreB64", "s_store_dwordx2"},
            {"SStoreB128", "s_store_dwordx4"},
            /* common.hpp */
            {"SAbsI32", "s_abs_i32"},
            {"SMaxI32", "s_max_i32"},
            {"SMaxU32", "s_max_u32"},
            {"SMinI32", "s_min_i32"},
            {"SMinU32", "s_min_u32"},
            {"SAddI32", "s_add_i32"},
            {"SAddU32", "s_add_u32"},
            {"SAddCU32", "s_addc_u32"},
            {"SMulI32", "s_mul_i32"},
            {"SMulHII32", "s_mul_hi_i32"},
            {"SMulHIU32", "s_mul_hi_u32"},
            {"SSubI32", "s_sub_i32"},
            {"SSubU32", "s_sub_u32"},
            {"SSubBU32", "s_subb_u32"},
            {"SCSelectB32", "s_cselect_b32"},
            {"SAndB32", "s_and_b32"},
            {"SAndB64", "s_and_b64"},
            {"SAndN2B32", "s_andn2_b32"},
            {"SOrB32", "s_or_b32"},
            {"SXorB32", "s_xor_b32"},
            {"SOrB64", "s_or_b64"},
            {"SGetPCB64", "s_getpc_b64"},
            {"SLShiftLeftB32", "s_lshl_b32"},
            {"SLShiftRightB32", "s_lshr_b32"},
            {"SLShiftLeftB64", "s_lshl_b64"},
            {"SLShiftRightB64", "s_lshr_b64"},
            {"SAShiftRightI32", "s_ashr_i32"},
            {"SLShiftLeft1AddU32", "s_lshl1_add_u32"},
            {"SLShiftLeft2AddU32", "s_lshl2_add_u32"},
            {"SLShiftLeft3AddU32", "s_lshl3_add_u32"},
            {"SLShiftLeft4AddU32", "s_lshl4_add_u32"},
            {"SSetMask", "s_set_mask"},
            {"SMovB32", "s_mov_b32"},
            {"SMovB64", "s_mov_b64"},
            {"SCMovB32", "s_cmov_b32"},
            {"SCMovB64", "s_cmov_b64"},
            {"SFf1B32", "s_ff1_i32_b32"},
            {"SBfmB32", "s_bfm_b32"},
            {"SMovkI32", "s_movk_i32"},
            {"SSExtI16toI32", "s_sext_i32_i16"},
            {"SAndSaveExecB64", "s_and_saveexec_b64"},
            {"SOrSaveExecB64", "s_or_saveexec_b64"},
            {"SSetPrior", "s_setprio"},
            {"SBarrier", "s_barrier"},
            {"SDcacheWb", "s_dcache_wb"},
            {"SNop", "s_nop"},
            {"SEndpgm", "s_endpgm"},
            {"SSleep", "s_sleep"},
            {"SGetRegB32", "s_getreg_b32"},
            {"SSetRegB32", "s_setreg_b32"},
            {"SSetRegIMM32B32", "s_setreg_imm32_b32"},
            {"SWaitCnt", "s_waitcnt"},
            {"SDelayAlu", "s_delay_alu"},
            {"VAddF16", "v_add_f16"},
            {"VAddF32", "v_add_f32"},
            {"VAddF64", "v_add_f64"},
            {"VAddI32", "v_add_i32"},
            {"VAddU32", "v_add_u32"},
            {"VAddCOU32", "v_add_co_u32"},
            {"VMulF16", "v_mul_f16"},
            {"VMulF32", "v_mul_f32"},
            {"VMulF64", "v_mul_f64"},
            {"VMulLOU32", "v_mul_lo_u32"},
            {"VMulHII32", "v_mul_hi_i32"},
            {"VMulHIU32", "v_mul_hi_u32"},
            {"VMulI32I24", "v_mul_i32_i24"},
            {"VMulU32U24", "v_mul_u32_u24"},
            {"VSubF32", "v_sub_f32"},
            {"VSubI32", "v_sub_i32"},
            {"VSubU32", "v_sub_u32"},
            {"VSubCoU32", "v_sub_co_u32"},
            {"VMacF32", "v_fmac_f32"},
            {"VDot2CF32F16", "v_dot2c_f32_f16"},
            {"VDot2F32F16", "v_dot2_f32_f16"},
            {"VFmaF16", "v_fma_f16"},
            {"VFmaF32", "v_fma_f32"},
            {"VFmaF64", "v_fma_f64"},
            {"VMadI32I24", "v_mad_i32_i24"},
            {"VMadU32U24", "v_mad_u32_u24"},
            {"VMadMixF32", "v_mad_mix_f32"},
            {"VExpF16", "v_exp_f16"},
            {"VExpF32", "v_exp_f32"},
            {"VRcpF16", "v_rcp_f16"},
            {"VRcpF32", "v_rcp_f32"},
            {"VRcpIFlagF32", "v_rcp_iflag_f32"},
            {"VRsqF16", "v_rsq_f16"},
            {"VRsqF32", "v_rsq_f32"},
            {"VMaxF16", "v_max_f16"},
            {"VMaxF32", "v_max_f32"},
            {"VMaxF64", "v_max_f64"},
            {"VMaxI32", "v_max_i32"},
            {"VMed3I32", "v_med3_i32"},
            {"VMed3F32", "v_med3_f32"},
            {"VMinF16", "v_min_f16"},
            {"VMinF32", "v_min_f32"},
            {"VMinF64", "v_min_f64"},
            {"VMinI32", "v_min_i32"},
            {"VAndB32", "v_and_b32"},
            {"VAndOrB32", "v_and_or_b32"},
            {"VNotB32", "v_not_b32"},
            {"VOrB32", "v_or_b32"},
            {"VXorB32", "v_xor_b32"},
            {"VCndMaskB32", "v_cndmask_b32"},
            {"VLShiftLeftB16", "v_lshlrev_b16"},
            {"VLShiftLeftB32", "v_lshlrev_b32"},
            {"VLShiftRightB32", "v_lshrrev_b32"},
            {"VLShiftLeftB64", "v_lshlrev_b64"},
            {"VLShiftRightB64", "v_lshrrev_b64"},
            {"VAShiftRightI32", "v_ashrrev_i32"},
            {"VLShiftLeftOrB32", "v_lshl_or_b32"},
            {"VAddLShiftLeftU32", "v_add_lshl_u32"},
            {"VLShiftLeftAddU32", "v_lshl_add_u32"},
            {"VMovB32", "v_mov_b32"},
            {"VMovB64", "v_mov_b64"},
            {"VSwapB32", "v_swap_b32"},
            {"VBfeI32", "v_bfe_i32"},
            {"VBfeU32", "v_bfe_u32"},
            {"VBfiB32", "v_bfi_b32"},
            {"VPackF16toB32", "v_pack_b32_f16"},
            {"VAccvgprReadB32", "v_accvgpr_read_b32"},
            {"VAccvgprWrite", "v_accvgpr_write_b32"},
            {"VAccvgprWriteB32", "v_accvgpr_write_b32"},
            {"VReadfirstlaneB32", "v_readfirstlane_b32"},
            {"VRndneF32", "v_rndne_f32"},
            {"VPermB32", "v_perm_b32"},
        };
        registry.setRocisaToArchMap(std::move(rocisaToArchMap));
    }

    void setGfx950LogicalToArchMap(GpuArch& registry)
    {
        std::unordered_map<std::string, std::string> logicalToHwInstMap = {
            {"VCvtScalePkFP8toF16", "v_cvt_scalef32_pk_f16_fp8"},
            {"VCvtScalePkBF8toF16", "v_cvt_scalef32_pk_f16_bf8"},
            {"VCvtScaleFP8toF16", "v_cvt_scalef32_f16_fp8"},
            {"VCvtScalePkF16toFP8", "v_cvt_scalef32_pk_fp8_f16"},
            {"VCvtScalePkF16toBF8", "v_cvt_scalef32_pk_bf8_f16"},
            {"VCvtScaleSRF16toFP8", "v_cvt_scalef32_sr_fp8_f16"},
            {"VCvtScaleSRF16toBF8", "v_cvt_scalef32_sr_bf8_f16"},
            {"VDot2F32BF16", "v_dot2_f32_bf16"},
            {"VDot2CF32BF16", "v_dot2c_f32_bf16"},
            {"PVCvtBF16toFP32", "v_cvt_f32_bf16"},
            {"VCvtPkF32toBF16", "v_cvt_pk_bf16_f32"},
            {"DSLoadB64TrB16", "ds_read_b64_tr_b16"},

            /*
            * Begin Import gfx942 instructions
            */

            /* branch.hpp */
            {"SBranch", "s_branch"},
            {"SCBranchSCC0", "s_cbranch_scc0"},
            {"SCBranchSCC1", "s_cbranch_scc1"},
            {"SCBranchVCCNZ", "s_cbranch_vccnz"},
            {"SCBranchVCCZ", "s_cbranch_vccz"},
            {"SSetPCB64", "s_setpc_b64"},
            {"SSwapPCB64", "s_swappc_b64"},
            {"SCBranchExecZ", "s_cbranch_execz"},
            {"SCBranchExecNZ", "s_cbranch_execnz"},

            /* cmp.hpp */
            {"SCmpEQI32", "s_cmp_eq_i32"},
            {"SCmpEQU32", "s_cmp_eq_u32"},
            {"SCmpEQU64", "s_cmp_eq_u64"},
            {"SCmpGeI32", "s_cmp_ge_i32"},
            {"SCmpGeU32", "s_cmp_ge_u32"},
            {"SCmpGtI32", "s_cmp_gt_i32"},
            {"SCmpGtU32", "s_cmp_gt_u32"},
            {"SCmpLeI32", "s_cmp_le_i32"},
            {"SCmpLeU32", "s_cmp_le_u32"},
            {"SCmpLgU32", "s_cmp_lg_u32"},
            {"SCmpLgI32", "s_cmp_lg_i32"},
            {"SCmpLgU64", "s_cmp_lg_u64"},
            {"SCmpLtI32", "s_cmp_lt_i32"},
            {"SCmpLtU32", "s_cmp_lt_u32"},
            {"SBitcmp1B32", "s_bitcmp1_b32"},
            {"SCmpKEQU32", "s_cmpk_eq_u32"},
            {"SCmpKGeU32", "s_cmpk_ge_u32"},
            {"SCmpKGtU32", "s_cmpk_gt_u32"},
            {"SCmpKLGU32", "s_cmpk_lg_u32"},
            {"VCmpEQF32", "v_cmp_eq_f32"},
            {"VCmpEQF64", "v_cmp_eq_f64"},
            {"VCmpEQU32", "v_cmp_eq_u32"},
            {"VCmpEQI32", "v_cmp_eq_i32"},
            {"VCmpGEF16", "v_cmp_ge_f16"},
            {"VCmpGTF16", "v_cmp_gt_f16"},
            {"VCmpGEF32", "v_cmp_ge_f32"},
            {"VCmpGTF32", "v_cmp_gt_f32"},
            {"VCmpGEF64", "v_cmp_ge_f64"},
            {"VCmpGTF64", "v_cmp_gt_f64"},
            {"VCmpGEI32", "v_cmp_ge_i32"},
            {"VCmpGTI32", "v_cmp_gt_i32"},
            {"VCmpGEU32", "v_cmp_ge_u32"},
            {"VCmpGtU32", "v_cmp_gt_u32"},
            {"VCmpLeU32", "v_cmp_le_u32"},
            {"VCmpLeI32", "v_cmp_le_i32"},
            {"VCmpLtI32", "v_cmp_lt_i32"},
            {"VCmpLtU32", "v_cmp_lt_u32"},
            {"VCmpUF32", "v_cmp_u_f32"},
            {"VCmpNeI32", "v_cmp_ne_i32"},
            {"VCmpNeU32", "v_cmp_ne_u32"},
            {"VCmpNeU64", "v_cmp_ne_u64"},
            {"VCmpClassF32", "v_cmp_class_f32"},
            {"VCmpXClassF32", "v_cmpx_class_f32"},
            {"VCmpXEqU32", "v_cmpx_eq_u32"},
            {"VCmpXGeU32", "v_cmpx_ge_u32"},
            {"VCmpXGtU32", "v_cmpx_gt_u32"},
            {"VCmpXLeU32", "v_cmpx_le_u32"},
            {"VCmpXLeI32", "v_cmpx_le_i32"},
            {"VCmpXLtF32", "v_cmpx_lt_f32"},
            {"VCmpXLtI32", "v_cmpx_lt_i32"},
            {"VCmpXLtU32", "v_cmpx_lt_u32"},
            {"VCmpXLtU64", "v_cmpx_lt_u64"},
            {"VCmpXNeU16", "v_cmpx_ne_u16"},
            {"VCmpXNeU32", "v_cmpx_ne_u32"},

            /* cvt.hpp */
            {"VCvtF16toF32", "v_cvt_f32_f16"},
            {"VCvtF32toF16", "v_cvt_f16_f32"},
            {"VCvtF32toU32", "v_cvt_u32_f32"},
            {"VCvtU32toF32", "v_cvt_f32_u32"},
            {"VCvtI32toF32", "v_cvt_f32_i32"},
            {"VCvtF32toI32", "v_cvt_i32_f32"},
            {"VCvtFP8toF32", "v_cvt_f32_fp8"},
            {"VCvtBF8toF32", "v_cvt_f32_bf8"},
            {"VCvtPkFP8toF32", "v_cvt_pk_f32_fp8"},
            {"VCvtPkBF8toF32", "v_cvt_pk_f32_bf8"},
            {"VCvtPkF32toFP8", "v_cvt_pk_fp8_f32"},
            {"VCvtPkF32toBF8", "v_cvt_pk_bf8_f32"},
            {"VCvtSRF32toFP8", "v_cvt_sr_fp8_f32"},
            {"VCvtSRF32toBF8", "v_cvt_sr_bf8_f32"},
            {"VCvtScalePkFP8toF16", "v_cvt_scalef32_pk_f16_fp8"},
            {"VCvtScalePkBF8toF16", "v_cvt_scalef32_pk_f16_bf8"},
            {"VCvtScaleFP8toF16", "v_cvt_scalef32_f16_fp8"},
            {"VCvtScalePkF16toFP8", "v_cvt_scalef32_pk_fp8_f16"},
            {"VCvtScalePkF16toBF8", "v_cvt_scalef32_pk_bf8_f16"},
            {"VCvtScaleSRF16toFP8", "v_cvt_scalef32_sr_fp8_f16"},
            {"VCvtScaleSRF16toBF8", "v_cvt_scalef32_sr_bf8_f16"},
            {"PVCvtBF16toFP32", "v_cvt_f32_bf16"},
            {"VCvtPkF32toBF16", "v_cvt_pk_bf16_f32"},

            /* mem.hpp */
            {"BufferLoadU8", "buffer_load_ubyte"},
            {"BufferLoadD16HII8", "buffer_load_sbyte_d16_hi"},
            {"BufferLoadD16HIU8", "buffer_load_ubyte_d16_hi"},
            {"BufferLoadD16I8", "buffer_load_sbyte_d16"},
            {"BufferLoadD16U8", "buffer_load_ubyte_d16"},
            {"BufferLoadD16HIB16", "buffer_load_short_d16_hi"},
            {"BufferLoadD16B16", "buffer_load_short_d16"},
            {"BufferLoadI8", "buffer_load_sbyte"},
            {"BufferLoadI16", "buffer_load_sshort"},
            {"BufferLoadU16", "buffer_load_ushort"},
            {"BufferLoadB32", "buffer_load_dword"},
            {"BufferLoadB64", "buffer_load_dwordx2"},
            {"BufferLoadB96", "buffer_load_b96"},
            {"BufferLoadB128", "buffer_load_dwordx4"},
            {"FlatLoadD16HII8", "flat_load_sbyte_d16_hi"},
            {"FlatLoadD16HIU8", "flat_load_ubyte_d16_hi"},
            {"FlatLoadD16I8", "flat_load_sbyte_d16"},
            {"FlatLoadD16U8", "flat_load_ubyte_d16"},
            {"FlatLoadD16HIB16", "flat_load_short_d16_hi"},
            {"FlatLoadD16B16", "flat_load_short_d16"},
            {"FlatLoadI8", "flat_load_sbyte"},
            {"FlatLoadI16", "flat_load_sshort"},
            {"FlatLoadU8", "flat_load_ubyte"},
            {"FlatLoadU16", "flat_load_ushort"},
            {"FlatLoadB32", "flat_load_dword"},
            {"FlatLoadB64", "flat_load_dwordx2"},
            {"FlatLoadB96", "flat_load_b96"},
            {"FlatLoadB128", "flat_load_dwordx4"},
            //{"GlobalLoadTR8B64", "global_load_tr8b64"},
            //{"GlobalLoadTR16B128", "global_load_tr16b128"},
            {"BufferStoreB8", "buffer_store_byte"},
            {"BufferStoreD16HIU8", "buffer_store_byte_d16_hi"},
            //{"BufferStoreD16U8", "buffer_store_d16u8"},
            {"BufferStoreD16HIB16", "buffer_store_short_d16_hi"},
            //{"BufferStoreD16B16", "buffer_store_d16b16"},
            {"BufferStoreB16", "buffer_store_short"},
            {"BufferStoreB32", "buffer_store_dword"},
            {"BufferStoreB64", "buffer_store_dwordx2"},
            {"BufferStoreB96", "buffer_store_b96"},
            {"BufferStoreB128", "buffer_store_dwordx4"},
            {"BufferAtomicAddF32", "buffer_atomic_add_f32"},
            {"BufferAtomicCmpswapB32", "buffer_atomic_cmpswap"},
            {"BufferAtomicCmpswapB64", "buffer_atomic_cmpswap_x2"},
            {"FlatStoreD16HIB16", "flat_store_short_d16_hi"},
            {"FlatStoreD16HIB8", "flat_store_byte_d16_hi"},
            {"FlatStoreB8", "flat_store_byte"},
            {"FlatStoreB16", "flat_store_short"},
            {"FlatStoreB32", "flat_store_dword"},
            {"FlatStoreB64", "flat_store_dwordx2"},
            {"FlatStoreB96", "flat_store_b96"},
            {"FlatStoreB128", "flat_store_dwordx4"},
            {"FlatAtomicCmpswapB32", "flat_atomic_cmpswap"},
            {"DSLoadU8", "ds_read_u8"},
            {"DSLoadD16HIU8", "ds_read_u8_d16_hi"},
            {"DSLoadU16", "ds_read_u16"},
            {"DSLoadD16HIU16", "ds_read_u16_d16_hi"},
            {"DSLoadB16", "ds_read_u16"},
            {"DSLoadB32", "ds_read_b32"},
            {"DSLoadB64", "ds_read_b64"},
            {"DSLoadB96", "ds_read_b96"},
            {"DSLoadI8", "ds_read_i8"},
            {"DSLoadI16", "ds_read_i16"},
            {"DSLoadB128", "ds_read_b128"},
            {"DSLoad2B32", "ds_read2_b32"},
            {"DSLoad2B64", "ds_read2_b64"},
            {"DSStoreU16", "ds_write_b16"},
            {"DSStoreB8", "ds_write_b8"},
            {"DSStoreB16", "ds_write_b16"},
            {"DSStoreB8HID16", "ds_write_b8_d16_hi"},
            {"DSStoreD16HIB16", "ds_write_b16_d16_hi"},
            {"DSStoreB32", "ds_write_b32"},
            {"DSStoreB64", "ds_write_b64"},
            {"DSStoreB96", "ds_write_b96"},
            {"DSStoreB128", "ds_write_b128"},
            {"DSStore2B32", "ds_write2_b32"},
            {"DSStore2B64", "ds_write2_b64"},
            {"DSBPermuteB32", "ds_bpermute_b32"},
            {"SAtomicDec", "s_atomic_dec"},
            {"SLoadB32", "s_load_dword"},
            {"SLoadB64", "s_load_dwordx2"},
            {"SLoadB128", "s_load_dwordx4"},
            {"SLoadB256", "s_load_dwordx8"},
            {"SLoadB512", "s_load_dwordx16"},
            {"SStoreB32", "s_store_dword"},
            {"SStoreB64", "s_store_dwordx2"},
            {"SStoreB128", "s_store_dwordx4"},
            // {"SStoreB256", "s_store_dwordx8"},
            // {"SStoreB512", "s_store_dwordx16"},

            /* common.hpp */
            {"SAbsI32", "s_abs_i32"},
            {"SMaxI32", "s_max_i32"},
            {"SMaxU32", "s_max_u32"},
            {"SMinI32", "s_min_i32"},
            {"SMinU32", "s_min_u32"},
            {"SAddI32", "s_add_i32"},
            {"SAddU32", "s_add_u32"},
            {"SAddCU32", "s_addc_u32"},
            {"SMulI32", "s_mul_i32"},
            {"SMulLOU32", "s_mul_lo_u32"},
            {"SMulHII32", "s_mul_hi_i32"},
            {"SMulHIU32", "s_mul_hi_u32"},
            {"SSubI32", "s_sub_i32"},
            {"SSubU64", "s_sub_u64"},
            {"SSubU32", "s_sub_u32"},
            {"SSubBU32", "s_subb_u32"},
            {"SCSelectB32", "s_cselect_b32"},
            {"SAndB32", "s_and_b32"},
            {"SAndB64", "s_and_b64"},
            {"SAndN2B32", "s_andn2_b32"},
            {"SOrB32", "s_or_b32"},
            {"SXorB32", "s_xor_b32"},
            {"SOrB64", "s_or_b64"},
            {"SGetPCB64", "s_getpc_b64"},
            {"SLShiftLeftB32", "s_lshl_b32"},
            {"SLShiftRightB32", "s_lshr_b32"},
            {"SLShiftLeftB64", "s_lshl_b64"},
            {"SLShiftRightB64", "s_lshr_b64"},
            {"SAShiftRightI32", "s_ashr_i32"},
            {"SLShiftLeft1AddU32", "s_lshl1_add_u32"},
            {"SLShiftLeft2AddU32", "s_lshl2_add_u32"},
            {"SLShiftLeft3AddU32", "s_lshl3_add_u32"},
            {"SLShiftLeft4AddU32", "s_lshl4_add_u32"},
            {"SSetMask", "s_set_mask"},
            {"SMovB32", "s_mov_b32"},
            {"SMovB64", "s_mov_b64"},
            {"SCMovB32", "s_cmov_b32"},
            {"SCMovB64", "s_cmov_b64"},
            {"SFf1B32", "s_ff1_i32_b32"},
            {"SBfmB32", "s_bfm_b32"},
            {"SMovkI32", "s_movk_i32"},
            {"SSExtI16toI32", "s_sext_i32_i16"},
            {"SAndSaveExecB32", "s_and_saveexec_b32"},
            {"SAndSaveExecB64", "s_and_saveexec_b64"},
            {"SOrSaveExecB32", "s_or_saveexec_b32"},
            {"SOrSaveExecB64", "s_or_saveexec_b64"},
            {"SSetPrior", "s_setprio"},
            {"SBarrier", "s_barrier"},
            {"SDcacheWb", "s_dcache_wb"},
            {"SNop", "s_nop"},
            {"SEndpgm", "s_endpgm"},
            {"SSleep", "s_sleep"},
            {"SGetRegB32", "s_getreg_b32"},
            {"SSetRegB32", "s_setreg_b32"},
            {"SSetRegIMM32B32", "s_setreg_imm32_b32"},
            {"SWaitCnt", "s_waitcnt"},
            //{"SWaitAlu", "s_wait_alu"},
            {"SDelayAlu", "s_delay_alu"},
            {"VAddF16", "v_add_f16"},
            {"VAddF32", "v_add_f32"},
            {"VAddF64", "v_add_f64"},
            {"VAddI32", "v_add_i32"},
            {"VAddU32", "v_add_u32"},
            {"VAddCOU32", "v_add_co_u32"},
            {"VAddCCOU32", "v_add_co_ci_u32"},
            {"VAdd3U32", "v_add3_u32"},
            {"VAddPKF16", "v_pk_add_f16"},
            {"VMulF16", "v_mul_f16"},
            {"VMulF32", "v_mul_f32"},
            {"VMulF64", "v_mul_f64"},
            {"VMulPKF16", "v_pk_mul_f16"},
            {"VMulPKF32S", "v_pk_mul_f32"},
            {"VMulLOU32", "v_mul_lo_u32"},
            {"VMulHII32", "v_mul_hi_i32"},
            {"VMulHIU32", "v_mul_hi_u32"},
            {"VMulI32I24", "v_mul_i32_i24"},
            {"VMulU32U24", "v_mul_u32_u24"},
            {"VSubF32", "v_sub_f32"},
            {"VSubI32", "v_sub_i32"},
            {"VSubU32", "v_sub_u32"},
            {"VSubCoU32", "v_sub_co_u32"},
            {"VMacF32", "v_fmac_f32"},
            {"VDot2CF32F16", "v_dot2c_f32_f16"},
            {"VDot2F32F16", "v_dot2_f32_f16"},
            {"VFmaF16", "v_fma_f16"},
            {"VFmaF32", "v_fma_f32"},
            {"VFmaF64", "v_fma_f64"},
            {"VFmaPKF16", "v_pk_fma_f16"},
            {"VFmaMixF32", "v_fma_mix_f32"},
            {"VMadI32I24", "v_mad_i32_i24"},
            {"VMadU32U24", "v_mad_u32_u24"},
            {"VMadMixF32", "v_mad_mix_f32"},
            {"VExpF16", "v_exp_f16"},
            {"VExpF32", "v_exp_f32"},
            {"VRcpF16", "v_rcp_f16"},
            {"VRcpF32", "v_rcp_f32"},
            {"VRcpIFlagF32", "v_rcp_iflag_f32"},
            {"VRsqF16", "v_rsq_f16"},
            {"VRsqF32", "v_rsq_f32"},
            {"VRsqIFlagF32", "v_rsq_iflag_f32"},
            {"VMaxF16", "v_max_f16"},
            {"VMaxF32", "v_max_f32"},
            {"VMaxF64", "v_max_f64"},
            {"VMaxI32", "v_max_i32"},
            {"VMaxPKF16", "v_pk_max_f16"},
            {"VMed3I32", "v_med3_i32"},
            {"VMed3F32", "v_med3_f32"},
            {"VMinF16", "v_min_f16"},
            {"VMinF32", "v_min_f32"},
            {"VMinF64", "v_min_f64"},
            {"VMinI32", "v_min_i32"},
            {"VAndB32", "v_and_b32"},
            {"VAndOrB32", "v_and_or_b32"},
            {"VNotB32", "v_not_b32"},
            {"VPrngB32", "v_prng_b32"},
            {"VOrB32", "v_or_b32"},
            {"VXorB32", "v_xor_b32"},
            {"VCndMaskB32", "v_cndmask_b32"},
            {"VLShiftLeftB16", "v_lshlrev_b16"},
            {"VLShiftLeftB32", "v_lshlrev_b32"},
            {"VLShiftRightB32", "v_lshrrev_b32"},
            {"VLShiftLeftB64", "v_lshlrev_b64"},
            {"VLShiftRightB64", "v_lshrrev_b64"},
            {"VAShiftRightI32", "v_ashrrev_i32"},
            {"VLShiftLeftOrB32", "v_lshl_or_b32"},
            {"VAddLShiftLeftU32", "v_add_lshl_u32"},
            {"VLShiftLeftAddU32", "v_lshl_add_u32"},
            {"VMovB32", "v_mov_b32"},
            {"VMovB64", "v_mov_b64"},
            {"VSwapB32", "v_swap_b32"},
            {"VBfeI32", "v_bfe_i32"},
            {"VBfeU32", "v_bfe_u32"},
            {"VBfiB32", "v_bfi_b32"},
            {"VPackF16toB32", "v_pack_b32_f16"},
            {"VAccvgprReadB32", "v_accvgpr_read_b32"},
            {"VAccvgprWrite", "v_accvgpr_write_b32"},
            {"VAccvgprWriteB32", "v_accvgpr_write_b32"},
            {"VReadfirstlaneB32", "v_readfirstlane_b32"},
            {"VRndneF32", "v_rndne_f32"},
            {"VPermB32", "v_perm_b32"},
        };

        registry.setLogicalToArchMap(std::move(logicalToHwInstMap));
    }

    void setGfx950ConversionMap(GpuArch& registry)
    {
        std::unordered_map<std::string, std::string> conversion = {
            {"_SWaitCnt", "lowerRocisaWaitCnt" /* todo */},
            {"_SWaitCntVscnt", "" /* todo */},
            {"_SWaitStorecnt", "" /* todo */},
            {"_SWaitLoadcnt", "" /* todo */},
            {"_SWaitKMcnt", "" /* todo */},
            {"_SWaitDscnt", "" /* todo */},

            // {"VMulPKF32", "v_pk_mul_f32" /* todo */},
            // {"VAddPKF32", "v_pk_add_f32" /* todo */},

            // {"VPrngB32", "v_prng_b32"},
            // {"VMaxPKF16", "v_max_pk_f16"},

            /* mfma.hpp */
            {"MFMAInstruction", "lowerRocisaMFMA"},
            {"SMFMAInstruction", "lowerRocisaMFMA"},
        };

        registry.setRocisaConversionMap(std::move(conversion));
    }

} // namespace stinkytofu
