/* ************************************************************************
 * Copyright (C) 2025-2026 Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * ************************************************************************ */
#pragma once

#include "ir/IntrinsicCall.hpp"
#include "ir/logical/LogicalInstructions.hpp"
#include <string>
#include <vector>

namespace stinkytofu
{
// ========================================================================
// Auto-generated factory functions for ALL IR instructions
// ========================================================================
// These return raw pointers for use by:
// - C++ projects: add directly to IRList
// - Python bindings: wrap in shared_ptr for automatic memory management
//
// Generated by TableGen from instruction definitions
// Includes both regular instructions (VAddU32, etc.) and special
// instructions (MFMA, MXMFMA, SMFMA, TensorLoadToLds, Label, IntrinsicCall)
#include "ir/LogicalInstructionFactory_generated.inc"

} // namespace stinkytofu
