/* ************************************************************************
 * Copyright (C) 2025-2026 Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * ************************************************************************ */
#pragma once

#include <memory>
#include <optional>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

#include "stinkytofu/core/Function.hpp"
#include "stinkytofu/core/IRBase.hpp"

namespace stinkytofu
{
    /**
     * @brief Assembly IR Module container
     *
     * StinkyAsmModule holds low-level, architecture-specific assembly instructions
     * (stinkytofu::IRBase*) that can be emitted as assembly text.
     *
     * This class provides a container for assembly instructions generated by
     * lowering passes or directly created through the StinkyTofu IR builders.
     *
     * Note: This class is planned for deprecation in favor of using Function/BasicBlock
     * directly, but is currently needed for compatibility with existing Python bindings
     * and rocisa conversion utilities.
     *
     * Architecture:
     *   LogicalModule (high-level IR) -> Lowering Passes -> StinkyAsmModule (assembly IR)
     *
     * Example usage:
     * @code
     *   auto module = std::make_shared<StinkyAsmModule>("myKernel");
     *
     *   // Add assembly instructions
     *   std::vector<IRBase*> insts = {...};
     *   module->add(insts);
     *
     *   // Generate assembly string
     *   std::string asm = module->emitAssembly();
     * @endcode
     */
    class StinkyAsmModule
    {
    public:
        /**
         * @brief Construct a new StinkyAsmModule
         * @param name Module/kernel name
         * @param arch Target GPU architecture [major, minor, stepping]
         */
        StinkyAsmModule(const std::string& name, const std::array<int, 3>& arch);

        /**
         * @brief Destructor - cleans up owned instructions
         */
        ~StinkyAsmModule();

        // Disable copy (we manage instruction ownership)
        StinkyAsmModule(const StinkyAsmModule&)            = delete;
        StinkyAsmModule& operator=(const StinkyAsmModule&) = delete;

        // Enable move
        StinkyAsmModule(StinkyAsmModule&&) noexcept;
        StinkyAsmModule& operator=(StinkyAsmModule&&) noexcept;

        /**
         * @brief Get the module name
         * @return Module name string
         */
        std::string getName() const;

        /**
         * @brief Get the target architecture
         * @return Architecture array [major, minor, stepping]
         */
        std::array<int, 3> getArch() const;

        /**
         * @brief Emit assembly code for all instructions
         * @return Assembly code as string
         */
        std::string emitAssembly() const;

        /**
         * @brief Run optimization pipeline on the module
         */
        void runOptimizationPipeline();

        /**
         * @brief Get the underlying Function
         *
         * This provides access to the internal Function representation.
         * The Function is owned by the StinkyAsmModule.
         *
         * @return Reference to the Function
         */
        Function& getFunction();

        const Function& getFunction() const;

        /**
         * @brief Add a group name to the module
         * @param name Group name
         */
        void addGroup(const std::string& name);

        /**
         * @brief Check if the module has the given group name
         * @param name Group name
         * @return True if the module has the given group name, false otherwise
         */
        bool hasGroup(const std::string& name) const;

        /**
         * @brief Find the range of instructions in the given group
         * @param groupName Group name
         * @return Optional range of instructions (begin, end) for the given group
         */
        std::optional<std::pair<IntrusiveListIterator<IRBase>, IntrusiveListIterator<IRBase>>>
            findGroupRange(const std::string& groupName) const;

        /**
         * @brief Update the group ranges
         * @param groups Group names if exists to update
         * @param instsCountBefore Number of instructions before updating
         */
        void updateInstructionGroups(const std::vector<const std::string*>& groups,
                                     size_t                                 instsCountBefore);

    private:
        struct Impl;
        std::unique_ptr<Impl> pImpl;
    };

} // namespace stinkytofu
