/* ************************************************************************
 * Copyright (C) 2025-2026 Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * ************************************************************************ */
#pragma once

#include <memory>
#include <optional>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

#include "stinkytofu/core/stinkytofu.hpp"

namespace stinkytofu
{
    /**
     * @brief Assembly IR Module container
     *
     * StinkyAsmModule holds low-level, architecture-specific assembly instructions
     * (stinkytofu::IRBase*) that can be emitted as assembly text.
     *
     * This class provides a container for assembly instructions generated by
     * lowering passes or directly created through the StinkyTofu IR builders.
     *
     * Note: This class is planned for deprecation in favor of using Function/BasicBlock
     * directly, but is currently needed for compatibility with existing Python bindings
     * and rocisa conversion utilities.
     *
     * Architecture:
     *   LogicalModule (high-level IR) -> Lowering Passes -> StinkyAsmModule (assembly IR)
     *
     * Example usage:
     * @code
     *   auto module = std::make_shared<StinkyAsmModule>("myKernel");
     *
     *   // Add assembly instructions
     *   std::vector<IRBase*> insts = {...};
     *   module->add(insts);
     *
     *   // Generate assembly string
     *   std::string asm = module->emitAssembly();
     * @endcode
     */
    class StinkyAsmModule
    {
    public:
        // Range of instructions in a group
        using GroupRange = std::pair<IntrusiveListIterator<IRBase>, IntrusiveListIterator<IRBase>>;

        /**
         * @brief Construct a new StinkyAsmModule
         * @param name Module/kernel name
         * @param arch Target GPU architecture [major, minor, stepping]
         */
        StinkyAsmModule(const std::string& name, const std::array<int, 3>& arch);

        /**
         * @brief Destructor - cleans up owned instructions
         */
        ~StinkyAsmModule();

        // Disable copy (we manage instruction ownership)
        StinkyAsmModule(const StinkyAsmModule&)            = delete;
        StinkyAsmModule& operator=(const StinkyAsmModule&) = delete;

        // Enable move
        StinkyAsmModule(StinkyAsmModule&&) noexcept;
        StinkyAsmModule& operator=(StinkyAsmModule&&) noexcept;

        /**
         * @brief Get the module name
         * @return Module name string
         */
        std::string getName() const;

        /**
         * @brief Get the target architecture
         * @return Architecture array [major, minor, stepping]
         */
        std::array<int, 3> getArch() const;

        /**
         * @brief Set the groups for a single assembly instruction
         *
         * @param inst Assembly instruction to set the groups for
         * @param groups Group indices to set for the instruction
         */
        void setInstructionGroups(IRBase* inst, const std::vector<int>& groups);

        /**
         * @brief Get all assembly instructions in this module (const version)
         * @return Vector of assembly instruction pointers
         */
        const std::vector<IRBase*>& getInstructions() const;

        /**
         * @brief Get number of instructions in this module
         * @return Instruction count
         */
        size_t size() const;

        /**
         * @brief Convert the object to its string representation.
         * @return String representation of the module instructions.
         */
        std::string toString() const;

        /**
         * @brief Emit assembly code for all instructions
         * @return Assembly code as string
         */
        std::string emitAssembly() const;

        /**
         * @brief Run optimization pipeline on the module
         */
        void runOptimizationPipeline();

        /**
         * @brief Get the underlying IRList
         *
         * This provides access to the internal IRList representation.
         * The IRList is owned by a Function/BasicBlock internally.
         *
         * @return Reference to the IRList
         */
        IRList& getIRList();

        /**
         * @brief Get the underlying IRList (const version)
         * @return Const reference to the IRList
         */
        const IRList& getIRList() const;

        /**
         * @brief Add a group name to the module
         * @param name Group name
         */
        void addGroup(const std::string& name);

        /**
         * @brief Get the group index by name
         * @param name Group name
         * @return Module group index
         */
        int getGroupIndex(const std::string& name) const;

        /**
         * @brief Check if the module has the given group name
         * @param name Group name
         * @return True if the module has the given group name, false otherwise
         */
        bool hasGroup(const std::string& name) const;

        /**
         * @brief Get the group name to index map
         * @return Group name to index map
         */
        const std::unordered_map<std::string, int>& getGroupNameIndexMap() const;

        /**
         * @brief Get the instruction groups by instruction pointer
         * @param inst Instruction pointer
         * @return Instruction groups
         */
        std::optional<std::unordered_set<int>> getInstructionGroups(IRBase* inst) const;

        /**
         * @brief Check if the instruction is in the given group
         * @param inst Instruction pointer
         * @param group Group index
         * @return True if the instruction is in the given group, false otherwise
         */
        bool isInstructionInGroup(const IRBase* inst, int group) const;

        /**
         * @brief Refresh the instruction groups
         */
        void refreshInstructionGroups();

        /**
         * @brief Find the range of instructions in the given group
         * @param groupName Group name
         * @return Pair of iterators to the beginning and end of the group range
         */
        GroupRange findGroupRange(const std::string& groupName);

    private:
        /**
         * @brief Find the range of instructions in the given group
         * @param groupIndex Group index
         * @return Pair of iterators to the beginning and end of the group range
         */
        GroupRange findGroupRange(int groupIndex);

        struct Impl;
        std::unique_ptr<Impl> pImpl;
    };

} // namespace stinkytofu
