/* ************************************************************************
 * Copyright (C) 2025-2026 Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * ************************************************************************ */
#pragma once

#include <memory>
#include <string>
#include <vector>

#include "stinkytofu.hpp"

namespace stinkytofu
{
    // Forward declarations
    class StinkyInstruction;

    /**
     * @brief Assembly IR Module container
     *
     * StinkyAsmModule holds low-level, architecture-specific assembly instructions
     * (stinkytofu::StinkyInstruction*) that can be emitted as assembly text.
     *
     * This class provides a container for assembly instructions generated by
     * lowering passes or directly created through the StinkyTofu IR builders.
     *
     * Note: This class is planned for deprecation in favor of using Function/BasicBlock
     * directly, but is currently needed for compatibility with existing Python bindings
     * and rocisa conversion utilities.
     *
     * Architecture:
     *   LogicalModule (high-level IR) -> Lowering Passes -> StinkyAsmModule (assembly IR)
     *
     * Example usage:
     * @code
     *   auto module = std::make_shared<StinkyAsmModule>("myKernel");
     *
     *   // Add assembly instructions
     *   std::vector<StinkyInstruction*> insts = {...};
     *   module->add(insts);
     *
     *   // Generate assembly string
     *   std::string asm = module->emitAssembly();
     * @endcode
     */
    class StinkyAsmModule
    {
    public:
        /**
         * @brief Construct a new StinkyAsmModule
         * @param name Module/kernel name
         * @param arch Target GPU architecture [major, minor, stepping]
         */
        StinkyAsmModule(const std::string& name, const std::array<int, 3>& arch);

        /**
         * @brief Destructor - cleans up owned instructions
         */
        ~StinkyAsmModule();

        // Disable copy (we manage instruction ownership)
        StinkyAsmModule(const StinkyAsmModule&)            = delete;
        StinkyAsmModule& operator=(const StinkyAsmModule&) = delete;

        // Enable move
        StinkyAsmModule(StinkyAsmModule&&) noexcept;
        StinkyAsmModule& operator=(StinkyAsmModule&&) noexcept;

        /**
         * @brief Get the module name
         * @return Module name string
         */
        std::string getName() const;

        /**
         * @brief Get the target architecture
         * @return Architecture array [major, minor, stepping]
         */
        std::array<int, 3> getArch() const;

        /**
         * @brief Add a single assembly instruction to this module
         *
         * The module takes shared ownership of the instruction.
         * Note: The instruction should already be in an IRList (BasicBlock).
         *
         * @param inst Assembly instruction to add
         */
        void add(StinkyInstruction* inst);

        /**
         * @brief Add multiple assembly instructions to this module
         *
         * The module takes shared ownership of all instructions.
         * Note: The instructions should already be in an IRList (BasicBlock).
         *
         * @param insts Vector of assembly instructions to add
         */
        void add(const std::vector<StinkyInstruction*>& insts);

        /**
         * @brief Get all assembly instructions in this module (const version)
         * @return Vector of assembly instruction pointers
         */
        const std::vector<StinkyInstruction*>& getInstructions() const;

        /**
         * @brief Get number of instructions in this module
         * @return Instruction count
         */
        size_t size() const;

        /**
         * @brief Convert the object to its string representation.
         * @return String representation of the module instructions.
         */
        std::string toString() const;

        /**
         * @brief Emit assembly code for all instructions
         * @return Assembly code as string
         */
        std::string emitAssembly() const;

        /**
         * @brief Run optimization pipeline on the module
         */
        void runOptimizationPipeline();

        /**
         * @brief Get the underlying IRList
         *
         * This provides access to the internal IRList representation.
         * The IRList is owned by a Function/BasicBlock internally.
         *
         * @return Reference to the IRList
         */
        IRList& getIRList();

        /**
         * @brief Get the underlying IRList (const version)
         * @return Const reference to the IRList
         */
        const IRList& getIRList() const;

    private:
        struct Impl;
        std::unique_ptr<Impl> pImpl;
    };

} // namespace stinkytofu
