/* ************************************************************************
 * Copyright (C) 2025-2026 Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * ************************************************************************ */

/**
 * @file IROpcode.hpp
 * @brief High-level IR opcode enumeration
 *
 * Similar to GFX:: enum for assembly IR, this provides a unified opcode
 * system for high-level IR instructions enabling fast pattern matching
 * via integer comparison instead of string comparison.
 */

#pragma once

#include <cstdint>
#include <string_view>

namespace stinkytofu
{

    /**
     * @brief High-Level IR Instruction Opcodes
     *
     * Each high-level IR instruction (VAddF32, VMulF32, etc.) has a unique
     * opcode for fast pattern matching and identification.
     *
     * Design notes:
     * - Similar to GFX:: enum for assembly IR
     * - Used by IRInstruction::getOpcode()
     * - Enables fast integer comparison in pattern matching
     * - Generated by tablegen from IRInstructionDefs.inc
     */
    namespace HLIR
    {
        enum Opcode : uint16_t
        {
            UNKNOWN = 0,

// Include generated opcode definitions
#include "IROpcodes_generated.inc"

            NUM_OPCODES // Sentinel value
        };

        /**
         * @brief Convert opcode to human-readable string
         * @param opcode The HLIR opcode
         * @return String representation (e.g., "VAddF32")
         */
        const char* getOpcodeName(Opcode opcode);

        /**
         * @brief Convert opcode to assembly mnemonic
         * @param opcode The HLIR opcode
         * @return Assembly mnemonic (e.g., "v_add_f32")
         */
        const char* getOpcodeMnemonic(Opcode opcode);

    } // namespace HLIR

} // namespace stinkytofu
