/* ************************************************************************
 * Copyright (C) 2025-2026 Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * ************************************************************************ */
#pragma once

#include "ir/asm/StinkyAsmIR.hpp" // For StinkyRegister definition
#include "ir/asm/StinkyModifiers.hpp"
#include "stinkytofu.hpp"
#include <iostream>
#include <optional>
#include <string>
#include <vector>

namespace stinkytofu
{

    /**
     * @brief Base class for all high-level IR instructions (architecture-independent)
     *
     * This is the LLVM-style high-level IR. Instructions at this level are:
     * - Architecture-independent (no arch-specific mnemonics)
     * - Logical operations (may be composite)
     * - Will be lowered to StinkyAsmIR (StinkyInstruction) by passes
     *
     * Design philosophy:
     * - Simple structs like rocisa (not heavy class hierarchies)
     * - Holds operands, modifiers, and metadata
     * - No virtual dispatch for lowering (use visitor pattern or type switch)
     */
    class IRInstruction : public IRBase
    {
    public:
        std::vector<StinkyRegister> dests; ///< Destination registers
        std::vector<StinkyRegister> srcs; ///< Source registers
        std::string                 comment; ///< Optional comment

        IRInstruction(IRType type)
            : IRBase(type)
        {
        }

        virtual ~IRInstruction() = default;

        /**
         * @brief Get the logical name of this instruction (for lowering)
         * @return Logical name like "VAddF32", "DSLoadB64"
         */
        virtual const char* getLogicalName() const
        {
            return "IRInstruction";
        }

        /**
         * @brief Check if this is a composite instruction that needs expansion
         * @return true if composite (expands to multiple instructions)
         */
        virtual bool isComposite() const
        {
            return false;
        }

        /**
         * @brief Virtual accessors for AMDGPU instruction modifiers
         *
         * These accessors allow safe access to instruction-specific modifiers
         * without dynamic_cast (works with -fno-rtti). These are instruction
         * semantics (how the instruction operates), not assembly scheduling hints.
         *
         * Examples:
         * - DPP: Data parallel processing (row shuffle, broadcast)
         * - SDWA: Sub-dword operand selection
         * - DS: LDS/GDS offsets and flags
         *
         * Generated instruction classes override these to return their modifiers.
         */
        virtual std::optional<DPPModifiers> getDPP() const
        {
            return std::nullopt;
        }

        virtual std::optional<SDWAModifiers> getSDWA() const
        {
            return std::nullopt;
        }

        virtual std::optional<DSModifiers> getDS() const
        {
            return std::nullopt;
        }
    };

} // namespace stinkytofu

// ========================================================================
// High-Level IR Instruction Definitions (Auto-generated by TableGen)
// ========================================================================
//
// All IR instruction classes are now generated from a single source of truth
// in tools/tablegen/GenHighLevelIR.cpp. This ensures consistency across:
// - IR class definitions
// - Builder method signatures
// - Mnemonic mappings for ToStinkyAsmPass
//
// To add a new instruction:
// 1. Update getIRInstructions() in tools/tablegen/GenHighLevelIR.cpp
// 2. Rebuild (TableGen runs automatically)
// 3. Done! IR class, builder, and mnemonics are all generated
//
// Note: The generated file has its own namespace stinkytofu block
#include "ir/StinkyInstructions_generated.hpp"
