#!/usr/bin/env python3

import pathlib
import sys


repo_dir = pathlib.Path(__file__).resolve().parent.parent
sys.path.append(str(repo_dir / "scripts" / "lib"))

import rrperf.cli  # noqa: E402

rrperf.cli.main()
