#!/bin/bash

# Runs all the CodeQL queries in rr-checks, saving results to cql.sarif .

# Installing the SARIF VSCode extension will display issues in a nice viewer format
# Alternatively: --format=csv

# export PATH=$PATH:/opt/codeql/codeql

codeql database analyze cql-data/rr-db cql/checks/rr-query-suites.qls \
    --format=sarifv2.1.0 --output=cql.sarif \
    --search-path=cql/checks \
     -j16 --rerun

sarif html cql.sarif
