#!/bin/bash -ex

# Installs CodeQL binaries in /opt/codeql
VERSION=v2.12.1
DESTINATION=/opt/codeql

mkdir -p $DESTINATION
cd $DESTINATION

curl -O -L https://github.com/github/codeql-cli-binaries/releases/download/$VERSION/codeql-linux64.zip
unzip codeql-linux64.zip
rm codeql-linux64.zip 

curl -o codeql-cli.zip -L https://github.com/github/codeql/archive/refs/tags/codeql-cli/$VERSION.zip
